import type { Course } from './types'

export const course: Course = {
  id: 'ap-physics-c-projectiles',
  title: 'Projectile Motion',
  lessons: [
    {
      id: 'projectile-shape',
      title: 'Shape of Projectiles',
      order: 1,
      description: 'Build intuition for parabolic paths by launching at different angles and speeds.',
      steps: [
        {
          id: 'shape-hook',
          type: 'intro',
          prompt: 'What shape does a projectile make?',
          body: 'Every thrown object follows the same curve — not a circle, not a straight line. Tap Launch and watch the trail.',
          simDefaults: {
            defaultAngle: 45,
            defaultVelocity: 15,
            angleRange: [15, 75],
            velocityRange: [10, 18],
            showMaxHeight: true,
          },
          feedback: {
            correct: 'Nice — you launched your first projectile!',
            incorrect: '',
            hint: '',
            explanation: 'Projectile paths are parabolas: symmetric curves caused by constant downward acceleration.',
          },
        },
        {
          id: 'shape-predict-shape',
          type: 'multiple_choice',
          prompt: 'What shape is the path of a projectile (ignoring air resistance)?',
          options: [
            { id: 'circle', label: 'A circle' },
            { id: 'parabola', label: 'A parabola' },
            { id: 'straight', label: 'A straight line' },
            { id: 'sine', label: 'A sine wave' },
          ],
          correctOptionId: 'parabola',
          feedback: {
            correct: 'Exactly — gravity pulls down at a constant rate, making a parabola.',
            incorrect: 'Not quite. Launch again and trace the trail with your eyes.',
            hint: 'Think about constant downward acceleration — the curve opens downward.',
            explanation:
              'With only gravity, horizontal speed stays constant while vertical speed decreases, then increases downward. That combination always gives a parabola.',
          },
        },
        {
          id: 'shape-gravity',
          type: 'sim_explore',
          prompt: 'What if gravity changed?',
          body: 'Gravity is what pulls projectiles into a parabola instead of a straight line. Use the sim to feel the difference between “no gravity” and Earth-like gravity.',
          tryItems: [
            'Set g = 0 m/s², launch, and watch the path.',
            'Set g = 10 m/s² (Earth) at the same angle and launch again.',
            'Notice how positive g curves the path downward.',
          ],
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 15,
            angleRange: [25, 65],
            velocityRange: [15, 15],
            showGravityControl: true,
            defaultGravity: 10,
            gravityRange: [0, 15],
            scaleAngle: 65,
            scaleVelocity: 15,
          },
          controls: ['angle'],
          feedback: {
            correct: 'Big difference — gravity is what bends the path into a parabola.',
            incorrect: '',
            hint: '',
            explanation:
              'With g = 0 there is no downward pull, so the projectile moves in a straight line. With g > 0, the path curves downward into a parabola.',
          },
        },
        {
          id: 'shape-predict-angle',
          type: 'multiple_choice',
          prompt: 'You keep speed the same but increase the launch angle. What happens to max height?',
          options: [
            { id: 'decrease', label: 'Max height decreases' },
            { id: 'same', label: 'Max height stays the same' },
            { id: 'increase', label: 'Max height increases' },
            { id: 'zero', label: 'The projectile never rises' },
          ],
          correctOptionId: 'increase',
          simConfig: {
            defaultAngle: 35,
            defaultVelocity: 18,
            angleRange: [15, 75],
            velocityRange: [18, 18],
            scaleAngle: 75,
            scaleVelocity: 18,
            showMaxHeight: true,
            rememberPreviousLaunch: true,
          },
          simControls: ['angle'],
          feedback: {
            correct: 'Right — a steeper launch puts more speed into the vertical direction.',
            incorrect: 'Try sliding the angle up in the sim and launching again.',
            hint: 'Higher angle → more vertical component of velocity at launch.',
            explanation:
              'At fixed speed, a larger launch angle means more initial vertical velocity, so the projectile climbs higher before falling.',
          },
        },
      ],
      capstone: [
        {
          id: 'shape-cap-1',
          type: 'capstone',
          subtype: 'multiple_choice',
          prompt: 'A cannon fires at 14 m/s. Which launch angle gives the highest arc (greatest max height)?',
          options: [
            { id: '15', label: '15°' },
            { id: '45', label: '45°' },
            { id: '60', label: '60°' },
            { id: '75', label: '75°' },
          ],
          correctOptionId: '75',
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 14,
            angleRange: [15, 75],
            velocityRange: [14, 14],
            scaleAngle: 75,
            scaleVelocity: 14,
            showMaxHeight: true,
            rememberPreviousLaunch: true,
          },
          simControls: ['angle'],
          feedback: {
            correct: '75° puts the most energy into going up — highest max height at the same speed.',
            incorrect: 'Use the sim: same speed, try steep vs shallow angles.',
            hint: 'Which angle points the cannon most upward?',
            explanation:
              'A steeper angle puts more launch speed into the vertical direction, so the projectile climbs higher.',
          },
        },
        {
          id: 'shape-cap-2',
          type: 'capstone',
          subtype: 'multiple_choice',
          prompt:
            'You keep the same launch angle but double the speed. What happens to the arc?',
          options: [
            { id: 'same', label: 'Stays the same size' },
            { id: 'shorter', label: 'Becomes shorter and lower' },
            { id: 'bigger', label: 'Goes farther and higher' },
            { id: 'straight', label: 'Becomes a straight line' },
          ],
          correctOptionId: 'bigger',
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 15,
            angleRange: [45, 45],
            velocityRange: [10, 25],
            scaleAngle: 45,
            scaleVelocity: 25,
            showMaxHeight: true,
            showLandingMarker: true,
            rememberPreviousLaunch: true,
          },
          simControls: ['velocity'],
          feedback: {
            correct: 'Right — more speed means more range and more height.',
            incorrect: 'Try launching at the same angle with a low vs high speed in the sim.',
            hint: 'Speed scales both horizontal and vertical motion.',
            explanation:
              'Doubling speed doubles both horizontal and vertical velocity components, so the projectile travels farther and climbs higher.',
          },
        },
      ],
    },
    {
      id: 'complementary-angles',
      title: 'Same Range, Two Angles',
      order: 2,
      description: 'Discover why complementary launch angles hit the same distance.',
      steps: [
        {
          id: 'comp-hook',
          type: 'intro',
          prompt: 'Two angles, one distance',
          body: 'Physicists love pairs: 30° and 60°, 25° and 65°… Try 30° first, then we’ll compare.',
          simDefaults: {
            defaultAngle: 30,
            defaultVelocity: 20,
            showLandingMarker: true,
            rememberPreviousLaunch: true,
            velocityRange: [20, 20],
            scaleVelocity: 20,
          },
          feedback: {
            correct: 'Good launch — remember how far it lands.',
            incorrect: '',
            hint: '',
            explanation: 'Complementary angles add to 90°. They share a surprising property for range.',
          },
        },
        {
          id: 'comp-explore',
          type: 'sim_explore',
          prompt: 'Compare 30° and 60° at the same speed',
          body: 'Complementary angles (add to 90°) can look very different but land at the same horizontal distance when speed is the same.',
          tryItems: [
            'Launch at 30° and note where the ball lands (orange flag).',
            'Switch to 60° and launch again — same landing spot, different arc.',
            'The orange dashed curve is your previous shot for easy comparison.',
          ],
          simConfig: {
            defaultAngle: 30,
            defaultVelocity: 20,
            angleRange: [15, 75],
            velocityRange: [20, 20],
            scaleAngle: 75,
            scaleVelocity: 20,
            showLandingMarker: true,
            rememberPreviousLaunch: true,
          },
          controls: ['angle'],
          feedback: {
            correct: 'Launch at 30°, then switch to 60° and launch again — same landing spot!',
            incorrect: '',
            hint: '',
            explanation: 'The orange dashed arc is your previous shot. Compare where each one lands.',
          },
        },
        {
          id: 'comp-discover',
          type: 'multiple_choice',
          prompt: 'At the same launch speed on level ground, 30° and 60° give…',
          options: [
            { id: 'diff-range', label: 'Different ranges; 60° always farther' },
            { id: 'same-range', label: 'The same horizontal range' },
            { id: 'same-height', label: 'The same max height' },
            { id: 'no-land', label: 'Neither reaches the ground' },
          ],
          correctOptionId: 'same-range',
          simConfig: {
            defaultAngle: 30,
            defaultVelocity: 20,
            angleRange: [20, 70],
            velocityRange: [20, 20],
            scaleAngle: 70,
            scaleVelocity: 20,
            showMaxHeight: true,
            showLandingMarker: true,
            rememberPreviousLaunch: true,
          },
          simControls: ['angle'],
          feedback: {
            correct: 'Yes! Complementary angles (θ and 90° − θ) share the same range.',
            incorrect: 'Launch both in the sim at 20 m/s and compare landing points.',
            hint: 'Try 30° and 60° — do they land at the same spot?',
            explanation:
              'For complementary angles, the horizontal range is the same even though the arc shapes differ.',
          },
        },
        {
          id: 'comp-summary',
          type: 'intro',
          prompt: 'The takeaway',
          body: 'Two complementary launch angles — θ and (90° − θ) — land at the same horizontal range when speed and launch height are the same. The arcs look different (one shallow, one steep), but the landing spot along the ground is identical.',
          feedback: {
            correct: 'That’s the key idea for this lesson!',
            incorrect: '',
            hint: '',
            explanation: 'Range depends on sin(2θ). Complementary angles give the same sin(2θ), so range matches.',
          },
        },
      ],
      capstone: [
        {
          id: 'comp-cap-1',
          type: 'capstone',
          subtype: 'multiple_choice',
          prompt: 'A projectile is fired at 25° to reach a target. Which angle gives the **same range** at the same speed?',
          options: [
            { id: '25', label: '25°' },
            { id: '55', label: '55°' },
            { id: '65', label: '65°' },
            { id: '115', label: '115°' },
          ],
          correctOptionId: '65',
          feedback: {
            correct: '65° = 90° − 25°. Complementary angles, same range.',
            incorrect: 'Complementary angles add to 90°.',
            hint: 'Same speed, level ground: look for 90° − 25°.',
            explanation: 'θ and 90°−θ produce identical range because sin(2θ) = sin(180°−2θ).',
          },
        },
        {
          id: 'comp-cap-2',
          type: 'capstone',
          subtype: 'sim_match',
          prompt: 'Match the ghost arc: set angle and speed so your shot lands at the same place as the 40° reference (20 m/s).',
          simConfig: {
            defaultAngle: 50,
            defaultVelocity: 20,
            angleRange: [15, 75],
            velocityRange: [20, 20],
            showGhostArc: true,
            ghostAngle: 40,
            ghostVelocity: 20,
            targetAngle: 50,
            targetVelocity: 20,
            showLandingMarker: true,
            rememberPreviousLaunch: true,
            scaleAngle: 75,
            scaleVelocity: 20,
          },
          feedback: {
            correct: '50° is complementary to 40° — same range, different arc shape!',
            incorrect: 'Keep speed at 20 m/s. Which angle pairs with 40°?',
            hint: 'Complementary to 40° means 90° − 40°.',
            explanation: '40° and 50° are complementary; at equal speed they share the same horizontal range.',
          },
        },
      ],
    },
    {
      id: 'projectile-calculations',
      title: 'Projectile Calculations',
      order: 3,
      description: 'Connect the simulation to range, height, and flight time with g = 10 m/s².',
      steps: [
        {
          id: 'calc-hook',
          type: 'intro',
          prompt: 'From intuition to numbers',
          body: 'You’ve seen the arcs. Now connect what you observe to a few key ideas — try the sim as you reason.',
          simDefaults: { defaultAngle: 45, defaultVelocity: 10, angleRange: [20, 70], velocityRange: [10, 10], showMaxHeight: true },
          feedback: {
            correct: 'Ready to calculate!',
            incorrect: '',
            hint: '',
            explanation: 'Key ideas: steeper angles go higher; 45° maximizes range; complementary angles share range.',
          },
        },
        {
          id: 'calc-predict-range',
          type: 'multiple_choice',
          prompt: 'At the same speed, which launch angle gives the greatest range on level ground?',
          options: [
            { id: '30', label: '30°' },
            { id: '45', label: '45°' },
            { id: '60', label: '60°' },
            { id: '75', label: '75°' },
          ],
          correctOptionId: '45',
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 15,
            angleRange: [20, 70],
            velocityRange: [15, 15],
            scaleAngle: 70,
            scaleVelocity: 15,
            showLandingMarker: true,
            rememberPreviousLaunch: true,
          },
          simControls: ['angle'],
          feedback: {
            correct: '45° maximizes range — try launching at 30°, 45°, and 60° in the sim.',
            incorrect: 'Use the sim: keep speed fixed and compare where each angle lands.',
            hint: 'Range is symmetric around 45° for complementary pairs.',
            explanation: 'At 45°, horizontal and vertical components are balanced for maximum range.',
          },
        },
        {
          id: 'calc-range-formula',
          type: 'range_formula',
          prompt: 'Why 45°?',
          body: 'On level ground with no air resistance, horizontal range is',
          formula: 'R = v² sin(2θ) / g',
          angleRange: [15, 75],
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 15,
            angleRange: [15, 75],
            velocityRange: [15, 15],
            scaleAngle: 75,
            scaleVelocity: 15,
            showLandingMarker: true,
            livePreview: true,
          },
          feedback: {
            correct: 'sin(2θ) peaks at θ = 45°, so range is greatest there.',
            incorrect: '',
            hint: '',
            explanation: 'Since R ∝ sin(2θ), the maximum occurs when sin(2θ) = 1, i.e. 2θ = 90° → θ = 45°.',
          },
        },
        {
          id: 'calc-connect',
          type: 'sim_explore',
          prompt: 'Check your numbers in the sim',
          body: 'You have formulas for range and height — now test them interactively. Range depends on angle through sin(2θ), and on speed through v².',
          tryItems: [
            'Try a few angles at fixed speed and watch where each shot lands.',
            'Change speed and see how range grows — is it proportional to v²? (We dive deeper into that in the next lesson.)',
            'Compare peak height when you change angle vs when you change speed.',
          ],
          simConfig: {
            defaultAngle: 30,
            defaultVelocity: 10,
            angleRange: [20, 60],
            velocityRange: [8, 15],
            scaleAngle: 60,
            scaleVelocity: 15,
            showMaxHeight: true,
            showLandingMarker: true,
            rememberPreviousLaunch: true,
          },
          controls: ['angle', 'velocity'],
          feedback: {
            correct: 'Sim and formulas agree — that’s physics working!',
            incorrect: '',
            hint: '',
            explanation: 'The simulation uses the same ideal equations you just calculated.',
          },
        },
      ],
      capstone: [
        {
          id: 'calc-cap-1',
          type: 'capstone',
          subtype: 'multiple_choice',
          prompt: 'A cannon fires at 20 m/s. Which angle gives the greatest range?',
          options: [
            { id: '20', label: '20°' },
            { id: '45', label: '45°' },
            { id: '60', label: '60°' },
            { id: '70', label: '70°' },
          ],
          correctOptionId: '45',
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 20,
            angleRange: [20, 70],
            velocityRange: [20, 20],
            scaleAngle: 70,
            scaleVelocity: 20,
            showLandingMarker: true,
            rememberPreviousLaunch: true,
          },
          simControls: ['angle'],
          feedback: {
            correct: '45° — maximum range at this speed.',
            incorrect: 'Launch at each angle in the sim and compare where the ball lands.',
            hint: 'Range is greatest when horizontal and vertical components are balanced.',
            explanation: 'For level ground with no air resistance, 45° gives the maximum range.',
          },
        },
        {
          id: 'calc-cap-2',
          type: 'capstone',
          subtype: 'numeric_input',
          prompt: 'Quick check: v = 10 m/s, θ = 15°, g = 10 m/s². Range in meters? (nearest whole number)',
          correctValue: 5,
          tolerance: 0.12,
          unit: 'm',
          feedback: {
            correct: 'Exactly 5 m — sin(30°) = 0.5 makes the arithmetic clean.',
            incorrect: 'Use R = v² sin(2θ) / g. Here 2θ = 30°.',
            hint: 'sin(30°) = 0.5, so R = 100 × 0.5 / 10.',
            explanation: 'R = 100 × sin(30°) / 10 = 100 × 0.5 / 10 = 5 m.',
          },
        },
      ],
    },
    {
      id: 'velocity-range-height',
      title: 'Speed, Range & Height',
      order: 4,
      description: 'See how launch speed and angle control range and maximum height.',
      steps: [
        {
          id: 'vel-hook',
          type: 'intro',
          prompt: 'Speed scales everything',
          body: 'Keep the angle fixed and slide speed — landing spot and peak height both grow. Range and max height depend on v and θ.',
          simDefaults: {
            defaultAngle: 45,
            defaultVelocity: 12,
            angleRange: [45, 45],
            velocityRange: [8, 18],
            showLandingMarker: true,
            rememberPreviousLaunch: true,
            scaleVelocity: 18,
          },
          feedback: {
            correct: 'Good — faster launch, farther landing.',
            incorrect: '',
            hint: '',
            explanation: 'Range R ∝ v² and max height H ∝ v² (at fixed angle), so speed has a big effect.',
          },
        },
        {
          id: 'vel-range-mc',
          type: 'multiple_choice',
          prompt: 'You double launch speed but keep the same angle. Range becomes…',
          options: [
            { id: '2x', label: '2× as far' },
            { id: '4x', label: '4× as far' },
            { id: 'same', label: 'The same' },
            { id: '8x', label: '8× as far' },
          ],
          correctOptionId: '4x',
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 10,
            angleRange: [45, 45],
            velocityRange: [8, 16],
            showLandingMarker: true,
            rememberPreviousLaunch: true,
            scaleVelocity: 16,
          },
          simControls: ['velocity'],
          feedback: {
            correct: 'Right — R ∝ v², so doubling v multiplies range by 4.',
            incorrect: 'Launch at 8 m/s, then 16 m/s in the sim and compare landing spots.',
            hint: 'Range has v² in the formula.',
            explanation: 'R = v² sin(2θ) / g. Doubling v quadruples v², so range becomes 4×.',
          },
        },
        {
          id: 'vel-formulas',
          type: 'formulas',
          prompt: 'Range and max height',
          body: 'On level ground (g = 10 m/s²), both formulas share the same v² factor when θ is held fixed:',
          formulas: [
            {
              label: 'Range',
              expression: 'R = v² sin(2θ) / g',
              note: 'R ∝ v² — double v → 4× the range',
            },
            {
              label: 'Max height',
              expression: 'H = v² sin²θ / (2g)',
              note: 'H ∝ v² — double v → 4× the peak height',
            },
          ],
          highlight:
            'Angle still matters (sin 2θ and sin²θ), but speed enters both formulas as v².',
          feedback: {
            correct: 'Both scale with v² — that’s why speed is so powerful.',
            incorrect: '',
            hint: '',
            explanation:
              'Range and max height both contain v². Tripling speed multiplies each by 9; doubling multiplies each by 4.',
          },
        },
        {
          id: 'vel-height-angle-mc',
          type: 'multiple_choice',
          prompt: 'At the same speed, which angle gives greater max height?',
          options: [
            { id: '30', label: '30°' },
            { id: '45', label: '45°' },
            { id: '60', label: '60°' },
            { id: 'same', label: 'All the same' },
          ],
          correctOptionId: '60',
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 14,
            angleRange: [25, 70],
            velocityRange: [14, 14],
            scaleAngle: 70,
            scaleVelocity: 14,
            showMaxHeight: true,
            rememberPreviousLaunch: true,
          },
          simControls: ['angle'],
          feedback: {
            correct: '60° — steeper means more vertical speed at launch.',
            incorrect: 'Try 30°, 45°, and 60° in the sim and watch the peak line.',
            hint: 'Max height depends on the vertical component of launch speed.',
            explanation: 'At fixed speed, H = (v sin θ)² / (2g). A larger θ puts more speed upward.',
          },
        },
        {
          id: 'vel-height-speed-mc',
          type: 'multiple_choice',
          prompt: 'Same angle — you double launch speed. Max height becomes…',
          options: [
            { id: '2x', label: '2× as high' },
            { id: '4x', label: '4× as high' },
            { id: 'same', label: 'The same' },
            { id: 'sqrt2', label: '√2× as high' },
          ],
          correctOptionId: '4x',
          simConfig: {
            defaultAngle: 50,
            defaultVelocity: 10,
            angleRange: [50, 50],
            velocityRange: [8, 16],
            scaleVelocity: 16,
            showMaxHeight: true,
            rememberPreviousLaunch: true,
          },
          simControls: ['velocity'],
          feedback: {
            correct: '4× — max height also scales with v².',
            incorrect: 'Compare peak heights at 8 m/s vs 16 m/s in the sim.',
            hint: 'H = (v sin θ)² / (2g). What happens when v doubles?',
            explanation: 'Max height is proportional to v² at fixed angle, just like range.',
          },
        },
      ],
      capstone: [
        {
          id: 'vel-cap-1',
          type: 'capstone',
          subtype: 'multiple_choice',
          prompt: 'A ball is launched at 45°. You triple the speed. Range is multiplied by…',
          options: [
            { id: '3', label: '3' },
            { id: '6', label: '6' },
            { id: '9', label: '9' },
            { id: '12', label: '12' },
          ],
          correctOptionId: '9',
          simConfig: {
            defaultAngle: 45,
            defaultVelocity: 10,
            angleRange: [45, 45],
            velocityRange: [10, 20],
            showLandingMarker: true,
            rememberPreviousLaunch: true,
            scaleVelocity: 20,
          },
          simControls: ['velocity'],
          feedback: {
            correct: '9× — tripling v gives v² factor of 9.',
            incorrect: 'Try 10 m/s vs 20 m/s (double first) in the sim, then think about tripling.',
            hint: 'R ∝ v². What is 3²?',
            explanation: 'Tripling speed multiplies v² by 9, so range becomes 9×.',
          },
        },
        {
          id: 'vel-cap-2',
          type: 'capstone',
          subtype: 'numeric_input',
          prompt: 'v = 10 m/s, θ = 45°, g = 10 m/s². Max height in meters? (nearest tenth)',
          correctValue: 2.5,
          unit: 'm',
          feedback: {
            correct: '2.5 m — vy = 10/√2, then H = vy² / (2g).',
            incorrect: 'H = (v sin θ)² / (2g). At 45°, sin θ = cos θ = √2/2.',
            hint: 'vy = v sin 45° ≈ 7.07 m/s. Then H = vy² / 20.',
            explanation: 'vy = 10 × 0.707 ≈ 7.07 m/s. H = 50 / 20 = 2.5 m.',
          },
        },
      ],
    },
  ],
}

export function getLessonById(lessonId: string) {
  return course.lessons.find((l) => l.id === lessonId)
}
